console.log(
  new URL(
    'https://www.google.com/search?q=google&oq=google&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIYCAEQLhhDGIMBGMcBGLEDGNEDGIAEGIoFMhIIAhAAGEMYgwEYsQMYgAQYigUyEggDEAAYQxiDARixAxiABBiKBTINCAQQABiDARixAxiABDIMCAUQABhDGIAEGIoFMg0IBhAAGIMBGLEDGIAEMg0IBxAAGIMBGLEDGIAEMg0ICBAAGIMBGLEDGIAEMg0ICRAAGIMBGLEDGIAE0gEHNTgzajBqN6gCAbACAQ&sourceid=chrome&ie=UTF-8'
  ).searchParams.entries()
);
